# Generated by Django 3.1.7 on 2021-03-18 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_first_name', models.CharField(max_length=50)),
                ('player_last_name', models.CharField(max_length=50)),
                ('age', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeamSeasonStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('pace', models.IntegerField(default=0)),
                ('offensive_rating', models.IntegerField(default=0)),
                ('defensive_rating', models.IntegerField(default=0)),
                ('coach', models.CharField(max_length=100)),
                ('team_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySport.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSeasonStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppg', models.FloatField(default=0)),
                ('apg', models.FloatField(default=0)),
                ('orb', models.FloatField(default=0)),
                ('rb', models.FloatField(default=0)),
                ('spg', models.FloatField(default=0)),
                ('bpg', models.FloatField(default=0)),
                ('tov', models.FloatField(default=0)),
                ('gp', models.FloatField(default=0)),
                ('mpg', models.FloatField(default=0)),
                ('fg', models.FloatField(default=0)),
                ('fga', models.FloatField(default=0)),
                ('fg_percentage', models.FloatField(default=0)),
                ('three_points', models.FloatField(default=0)),
                ('three_points_attempted', models.FloatField(default=0)),
                ('three_points_perctange', models.FloatField(default=0)),
                ('two_points', models.FloatField(default=0)),
                ('two_points_attempted', models.FloatField(default=0)),
                ('two_point_perctange', models.FloatField(default=0)),
                ('ft', models.FloatField(default=0)),
                ('fta', models.FloatField(default=0)),
                ('ft_percentage', models.FloatField(default=0)),
                ('player_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySport.player')),
                ('team_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mySport.team')),
            ],
        ),
    ]
