# Generated by Django 3.1.7 on 2021-03-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_last_name',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='age',
        ),
        migrations.AddField(
            model_name='playerseasonstats',
            name='age',
            field=models.IntegerField(default=19),
        ),
        migrations.AddField(
            model_name='playerseasonstats',
            name='season',
            field=models.CharField(default='NA', max_length=10),
        ),
    ]
