# Generated by Django 3.1.7 on 2021-03-21 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySport', '0002_auto_20210321_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerseasonstats',
            old_name='apg',
            new_name='APG',
        ),
        migrations.RenameField(
            model_name='playerseasonstats',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='playerseasonstats',
            old_name='bpg',
            new_name='BPG',
        ),
        migrations.RenameField(
            model_name='playerseasonstats',
            old_name='fg',
            new_name='FG',
        ),
        migrations.RenameField(
            model_name='playerseasonstats',
            old_name='fga',
            new_name='FGA',
        ),
        migrations.RenameField(
            model_name='playerseasonstats',
            old_name='fg_percentage',
            new_name='FG_percentage',
        ),
        migrations.RenameField(
            model_name='playerseasonstats',
            old_name='ft',
            new_name='FT',
        ),
        migrations.RenameField(
            model_name='playerseasonstats',
            old_name='fta',
            new_name='FTA',
        ),
        migrations.RenameField(
            model_name='playerseasonstats',
            old_name='ft_percentage',
            new_name='FT_percentage',
        ),
        migrations.RenameField(
            model_name='playerseasonstats',
            old_name='gp',
            new_name='GP',
        ),
        migrations.RenameField(
            model_name='playerseasonstats',
            old_name='mpg',
            new_name='MPG',
        ),
        migrations.RenameField(
            model_name='playerseasonstats',
            old_name='orb',
            new_name='ORB',
        ),
        migrations.RenameField(
            model_name='playerseasonstats',
            old_name='ppg',
            new_name='PPG',
        ),
        migrations.RenameField(
            model_name='playerseasonstats',
            old_name='spg',
            new_name='SPG',
        ),
        migrations.RenameField(
            model_name='playerseasonstats',
            old_name='season',
            new_name='Season',
        ),
        migrations.RenameField(
            model_name='playerseasonstats',
            old_name='tov',
            new_name='TOV',
        ),
        migrations.RenameField(
            model_name='playerseasonstats',
            old_name='rb',
            new_name='TRB',
        ),
        migrations.RenameField(
            model_name='playerseasonstats',
            old_name='player_ID',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='playerseasonstats',
            old_name='team_ID',
            new_name='team',
        ),
    ]
