# Generated by Django 3.1.7 on 2021-03-21 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySport', '0003_auto_20210321_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerseasonstats',
            old_name='three_points',
            new_name='three_points_made',
        ),
        migrations.RenameField(
            model_name='playerseasonstats',
            old_name='two_points',
            new_name='two_points_made',
        ),
    ]
