# Generated by Django 3.1.7 on 2021-03-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySport', '0004_auto_20210321_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerseasonstats',
            old_name='three_points_perctange',
            new_name='three_points_percentage',
        ),
        migrations.RenameField(
            model_name='playerseasonstats',
            old_name='two_point_perctange',
            new_name='two_point_percentage',
        ),
        migrations.AddField(
            model_name='playerseasonstats',
            name='PF',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='playerseasonstats',
            name='position',
            field=models.CharField(default='NA', max_length=10),
        ),
    ]
