# Generated by Django 3.1.7 on 2021-03-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySport', '0006_auto_20210321_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerseasonstats',
            old_name='Season',
            new_name='season',
        ),
        migrations.AddField(
            model_name='team',
            name='short_form',
            field=models.CharField(default='NAN', max_length=4),
            preserve_default=False,
        ),
    ]
