# Generated by Django 3.1.7 on 2021-03-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySport', '0007_auto_20210324_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerseasonstats',
            name='team_name',
            field=models.CharField(default='NAN', max_length=4),
        ),
    ]
