# Generated by Django 3.1.7 on 2021-03-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySport', '0009_player_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseasonstats',
            name='playoffs',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
