# Generated by Django 3.1.7 on 2021-03-25 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySport', '0010_teamseasonstats_playoffs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamseasonstats',
            old_name='team_ID',
            new_name='team',
        ),
    ]
