# Generated by Django 3.1.7 on 2021-03-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySport', '0012_auto_20210325_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamseasonstats',
            name='pace',
            field=models.FloatField(default=0.0),
        ),
    ]
