# Generated by Django 3.1.7 on 2021-04-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySport', '0016_auto_20210402_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.CharField(default='https://theundefeated.com/wp-content/uploads/2017/06/nbalogo.jpg?w=700', max_length=150),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='GP',
            field=models.IntegerField(default=0),
        ),
    ]
