# Generated by Django 3.1.7 on 2021-04-03 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mySport', '0017_auto_20210402_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='teamovr',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('winningSeasons', models.IntegerField()),
                ('losingSeasons', models.IntegerField()),
                ('championshipsWon', models.IntegerField()),
                ('championshipApps', models.IntegerField()),
                ('yearsInLeague', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mySport.team')),
            ],
        ),
    ]
