# Generated by Django 3.1.7 on 2021-04-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySport', '0018_teamovr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamseasonstats',
            name='defensive_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='teamseasonstats',
            name='losses',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teamseasonstats',
            name='offensive_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='teamseasonstats',
            name='pace',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='teamseasonstats',
            name='wins',
            field=models.IntegerField(null=True),
        ),
    ]
