# Generated by Django 3.1.7 on 2021-04-12 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mySport', '0020_auto_20210412_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='playerovr',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('averageAssits', models.IntegerField()),
                ('averageTOV', models.IntegerField()),
                ('averageSteals', models.IntegerField()),
                ('averageBlocks', models.IntegerField()),
                ('averagePoints', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mySport.player')),
            ],
        ),
    ]
